version: '2'
services:
    fixit-app:
        image: fixit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fixit-postgresql:5432/FixIt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fixit-postgresql:
        extends:
            file: postgresql.yml
            service: fixit-postgresql
